---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_config:
    network:
      private_network: "ip: '10.30.0.11'"
  run_list: ["recipe[apt]"]
  attributes:
    corosync:
      bindnetaddr: '10.30.0.11'
- name: centos-6.5
  driver_config:
    network:
      private_network: "ip: '10.30.0.12'"
  attributes:
    corosync:
      bindnetaddr: '10.30.0.12'
- name: debian-7.4
  driver_config:
    network:
      private_network: "ip: '10.30.0.13'"
  run_list: ["recipe[debian]"]
  attributes:
    corosync:
      bindnetaddr: '10.30.0.13'

suites:
- name: default
  run_list: ["recipe[corosync]"]
  attributes: 
    corosync:
      members:
      - '10.30.0.11'
      - '10.30.0.12'
      - '10.30.0.13'
      version: 1
  data_bags_path: 'test/integration/data_bags'
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
